// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvqKmvPShgyvKnSanwngCCISxHgn5M30M',
    appId: '1:642207065144:web:3613ef65b239cfc209b2cd',
    messagingSenderId: '642207065144',
    projectId: 'reduce-waste-app-ddc36',
    authDomain: 'reduce-waste-app-ddc36.firebaseapp.com',
    storageBucket: 'reduce-waste-app-ddc36.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_kUpR-C1w7FLMALHlg5QzeuDFLYxT5fI',
    appId: '1:642207065144:android:92149a0d4e1bcc8e09b2cd',
    messagingSenderId: '642207065144',
    projectId: 'reduce-waste-app-ddc36',
    storageBucket: 'reduce-waste-app-ddc36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbF6uArWyTC-zUxiVk1pNBIu1PkGPJOuU',
    appId: '1:642207065144:ios:f8950a9ef5c2ddb709b2cd',
    messagingSenderId: '642207065144',
    projectId: 'reduce-waste-app-ddc36',
    storageBucket: 'reduce-waste-app-ddc36.firebasestorage.app',
    iosBundleId: 'com.example.wasteReduceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbF6uArWyTC-zUxiVk1pNBIu1PkGPJOuU',
    appId: '1:642207065144:ios:f8950a9ef5c2ddb709b2cd',
    messagingSenderId: '642207065144',
    projectId: 'reduce-waste-app-ddc36',
    storageBucket: 'reduce-waste-app-ddc36.firebasestorage.app',
    iosBundleId: 'com.example.wasteReduceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvqKmvPShgyvKnSanwngCCISxHgn5M30M',
    appId: '1:642207065144:web:5c3c14c7acdf754309b2cd',
    messagingSenderId: '642207065144',
    projectId: 'reduce-waste-app-ddc36',
    authDomain: 'reduce-waste-app-ddc36.firebaseapp.com',
    storageBucket: 'reduce-waste-app-ddc36.firebasestorage.app',
  );
}
